Uncaught exception
Traceback (most recent call last):
  File "/home/francesco/Desktop/TESI/Schedulers/validate.py", line 140, in <module>
    main()
  File "/home/francesco/Desktop/TESI/Schedulers/validate.py", line 135, in main
    d = tiling(a, b, c)
  File "/home/francesco/Desktop/TESI/Schedulers/validate.py", line 112, in tiling
    d = gpu_kernel_execution(a, b, c, CTAs, tensor)
  File "/home/francesco/Desktop/TESI/Schedulers/validate.py", line 67, in gpu_kernel_execution
    for CTA in CTAs:
TypeError: 'NoneType' object is not iterable
